name: CI Check

on:
  push:
    branches: ["main"]

jobs:
  typecheck:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run : npx expo lint
      - run : npx expo typecheck

      # npx expo lint
      # npx expo typecheck


